/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    authors: Author;
    categories: Category;
    tags: Tag;
    posts: Post;
    'short-stories': ShortStory;
    'feed-decorations': FeedDecoration;
    'decoration-packs': DecorationPack;
    projects: Project;
    things: Thing;
    videos: Video;
    pages: Page;
    links: Link;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'short-stories': ShortStoriesSelect<false> | ShortStoriesSelect<true>;
    'feed-decorations': FeedDecorationsSelect<false> | FeedDecorationsSelect<true>;
    'decoration-packs': DecorationPacksSelect<false> | DecorationPacksSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    things: ThingsSelect<false> | ThingsSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    links: LinksSelect<false> | LinksSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'vi') | ('en' | 'vi')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'vi';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Authentication accounts. Only Admins can manage users and roles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * admin: full access · manager: editorial · creator: own drafts only
   */
  role: 'admin' | 'manager' | 'creator';
  /**
   * Inactive users cannot log in or access the Admin panel.
   */
  active?: boolean | null;
  avatar?: (number | null) | Media;
  /**
   * Notes visible to Admins only.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Files stored in Cloudflare R2. SVG uploads are disallowed. Crop/focal-point transforms are disabled (no sharp on Workers).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Required accessibility text for images.
   */
  alt: string;
  caption?: string | null;
  credit?: string | null;
  kind?: ('image' | 'document' | 'video' | 'other') | null;
  /**
   * Optional original source URL for attribution.
   */
  sourceUrl?: string | null;
  /**
   * Optional #RRGGBB placeholder color for progressive loading.
   */
  dominantColor?: string | null;
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * Public-safe author profiles. Never expose auth emails or roles here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  displayName: string;
  jobTitle?: string | null;
  bio?: string | null;
  avatar?: (number | null) | Media;
  website?: string | null;
  socialLinks?:
    | {
        platform:
          | 'github'
          | 'linkedin'
          | 'x'
          | 'youtube'
          | 'facebook'
          | 'instagram'
          | 'tiktok'
          | 'threads'
          | 'website'
          | 'other';
        url: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Linked auth user (Admin only).
   */
  user?: (number | null) | User;
  /**
   * Only approved profiles are publicly readable.
   */
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  /**
   * Optional hex color, e.g. #3366FF
   */
  color?: string | null;
  icon?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Short summary used in listings and SEO fallbacks.
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  relatedPosts?: (number | Post)[] | null;
  /**
   * Search and social metadata. Frontend rendering (meta tags, sitemap, hreflang) comes later.
   */
  seo?: {
    /**
     * Recommended 50–60 characters. Falls back to document title.
     */
    metaTitle?: string | null;
    /**
     * Recommended 140–160 characters. Falls back to excerpt/summary.
     */
    metaDescription?: string | null;
    /**
     * Optional absolute canonical URL override.
     */
    canonicalUrl?: string | null;
    /**
     * Open Graph title override. Falls back to meta title / title.
     */
    ogTitle?: string | null;
    /**
     * Open Graph description override.
     */
    ogDescription?: string | null;
    /**
     * Open Graph image. Falls back to the page image.
     */
    ogImage?: (number | null) | Media;
    twitterCard?: ('summary' | 'summary_large_image') | null;
    /**
     * Prevent search engines from indexing this document.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
    structuredData?: {
      /**
       * JSON-LD headline override.
       */
      headline?: string | null;
      description?: string | null;
      /**
       * Optional raw JSON-LD object (Admin/Manager only). Must be valid JSON.
       */
      jsonLdOverride?: string | null;
    };
  };
  author?: (number | null) | Author;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  featured?: boolean | null;
  /**
   * Estimated minutes; calculated from content.
   */
  readingTime?: number | null;
  /**
   * Set automatically on first publish. Managers may override.
   */
  publishedAt?: string | null;
  /**
   * Optional original publication date if republishing older content.
   */
  originalPublishedAt?: string | null;
  /**
   * Internal ownership for Creator access control. Hidden from public APIs via select.
   */
  owner?: (number | null) | User;
  /**
   * Editorial signal only.
   */
  translationReady?: {
    vi?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Compact feed fillers used to pack empty regions in the homepage bento grid.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "short-stories".
 */
export interface ShortStory {
  id: number;
  title: string;
  /**
   * Keep this short — it appears inside a compact feed tile.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  variant: 'note' | 'quote' | 'image';
  /**
   * Required for image-variant stories in practice; optional for others.
   */
  image?: (number | null) | Media;
  /**
   * Optional destination when the story tile is clicked.
   */
  link?: {
    enabled?: boolean | null;
    label?: string | null;
    linkType?: ('external' | 'internal') | null;
    page?: (number | null) | Page;
    url?: string | null;
    newTab?: boolean | null;
  };
  /**
   * Set automatically on first publish. Managers may override.
   */
  publishedAt?: string | null;
  /**
   * Internal ownership for Creator access control. Hidden from public APIs via select.
   */
  owner?: (number | null) | User;
  /**
   * Editorial signal only.
   */
  translationReady?: {
    vi?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Home template documents power `/` and `/vi` via layout blocks. Other templates render at `/[slug]` and `/vi/[slug]`.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  summary?: string | null;
  /**
   * Shared page image used as the hero/backdrop and as the OG image fallback.
   */
  pageImage?: (number | null) | Media;
  layout?:
    | (
        | {
            /**
             * Small label above the title (e.g. “Hero”).
             */
            label?: string | null;
            title: string;
            tagline?: string | null;
            bio?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            heroImage?: (number | null) | Media;
            /**
             * Pick links from the Links library.
             */
            links?: (number | Link)[] | null;
            /**
             * Cursor popup text while hovering this section.
             */
            cursorPopup?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading: string;
            /**
             * Optional short blurb shown below the section heading.
             */
            description?: string | null;
            /**
             * Posts/Projects/Videos use the feed grid. Things uses a custom showcase layout with the same source logic.
             */
            feedType: 'posts' | 'projects' | 'things' | 'videos';
            source: 'latest' | 'featured' | 'manual';
            /**
             * Static shows a capped preview (optionally with View all). Infinite loads more as the visitor scrolls — only available for latest published.
             */
            pagination?: ('static' | 'infinite') | null;
            /**
             * Initial item count. For static previews this is the full grid size; for infinite scroll it is the first page size.
             */
            limit: number;
            showViewAll?: boolean | null;
            /**
             * Label for the trailing tile (e.g. “View all posts”).
             */
            viewAllLabel?: string | null;
            /**
             * CMS page the View all tile links to (e.g. Posts or Projects index page).
             */
            viewAllPage?: (number | null) | Page;
            postItems?: (number | Post)[] | null;
            projectItems?: (number | Project)[] | null;
            /**
             * Homepage Things showcase uses up to 5 tiles plus an optional View all tile.
             */
            thingItems?: (number | Thing)[] | null;
            videoItems?: (number | Video)[] | null;
            /**
             * While hovering the section (header / grid chrome).
             */
            cursorPopup?: string | null;
            /**
             * When the section has no items yet.
             */
            cursorPopupEmpty?: string | null;
            /**
             * While hovering an individual feed tile.
             */
            cursorPopupItem?: string | null;
            /**
             * While hovering the “View all” tile.
             */
            cursorPopupViewAll?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'feedSection';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            media: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'media';
          }
        | {
            heading: string;
            body?: string | null;
            /**
             * Pick up to 3 links from the Links library.
             */
            links?: (number | Link)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
        | {
            heading?: string | null;
            items?: (number | Project)[] | null;
            featuredOnly?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'projectsGrid';
          }
        | {
            /**
             * Pick the short stories to cycle through. Order is preserved.
             */
            stories: (number | ShortStory)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'typewriter';
          }
        | {
            /**
             * Pick the short stories to display. Each one scrambles on hover. Order is preserved.
             */
            stories: (number | ShortStory)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'scramble-hover';
          }
        | {
            /**
             * CSS height for the blank section (e.g. 60vh, 400px, 5rem).
             */
            height?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'blankSpace';
          }
        | {
            footerText?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Pick legal links from the Links library.
             */
            legalLinks?: (number | Link)[] | null;
            /**
             * Use {{year}} as a placeholder for the current year in the frontend.
             */
            copyright?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'footer';
          }
      )[]
    | null;
  /**
   * Search and social metadata. Frontend rendering (meta tags, sitemap, hreflang) comes later.
   */
  seo?: {
    /**
     * Recommended 50–60 characters. Falls back to document title.
     */
    metaTitle?: string | null;
    /**
     * Recommended 140–160 characters. Falls back to excerpt/summary.
     */
    metaDescription?: string | null;
    /**
     * Optional absolute canonical URL override.
     */
    canonicalUrl?: string | null;
    /**
     * Open Graph title override. Falls back to meta title / title.
     */
    ogTitle?: string | null;
    /**
     * Open Graph description override.
     */
    ogDescription?: string | null;
    /**
     * Open Graph image. Falls back to the page image.
     */
    ogImage?: (number | null) | Media;
    twitterCard?: ('summary' | 'summary_large_image') | null;
    /**
     * Prevent search engines from indexing this document.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  /**
   * Home powers `/` and `/vi`. Only one published Home page is allowed; it must include exactly one Hero block.
   */
  template: 'home' | 'about' | 'contact' | 'generic';
  /**
   * Set automatically on first publish. Managers may override.
   */
  publishedAt?: string | null;
  /**
   * Editorial signal only.
   */
  translationReady?: {
    vi?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Centralized link library. Reference these from navigation, hero, CTA, and footer blocks.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links".
 */
export interface Link {
  id: number;
  /**
   * Visible label rendered on the public site.
   */
  label: string;
  /**
   * Hint for which surfaces typically show this link. Picker fields may filter by category.
   */
  category?: ('navigation' | 'social' | 'legal' | 'contact' | 'other') | null;
  linkType: 'internal' | 'external';
  page?: (number | null) | Page;
  url?: string | null;
  newTab?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  summary: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedProjects?: (number | Project)[] | null;
  /**
   * Search and social metadata. Frontend rendering (meta tags, sitemap, hreflang) comes later.
   */
  seo?: {
    /**
     * Recommended 50–60 characters. Falls back to document title.
     */
    metaTitle?: string | null;
    /**
     * Recommended 140–160 characters. Falls back to excerpt/summary.
     */
    metaDescription?: string | null;
    /**
     * Optional absolute canonical URL override.
     */
    canonicalUrl?: string | null;
    /**
     * Open Graph title override. Falls back to meta title / title.
     */
    ogTitle?: string | null;
    /**
     * Open Graph description override.
     */
    ogDescription?: string | null;
    /**
     * Open Graph image. Falls back to the page image.
     */
    ogImage?: (number | null) | Media;
    twitterCard?: ('summary' | 'summary_large_image') | null;
    /**
     * Prevent search engines from indexing this document.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  author?: (number | null) | Author;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  featured?: boolean | null;
  /**
   * Set automatically on first publish. Managers may override.
   */
  publishedAt?: string | null;
  /**
   * Internal ownership for Creator access control. Hidden from public APIs via select.
   */
  owner?: (number | null) | User;
  /**
   * Editorial signal only.
   */
  translationReady?: {
    vi?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Products and tools you use — affiliate links are localized (Amazon / Shopee).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "things".
 */
export interface Thing {
  id: number;
  name: string;
  /**
   * Short blurb shown in the Things showcase panel.
   */
  description?: string | null;
  /**
   * Large showcase image (left / top).
   */
  primaryImage: number | Media;
  /**
   * Optional smaller panel image. Falls back to the primary image when empty.
   */
  detailImage?: (number | null) | Media;
  /**
   * Localized shop link (e.g. Amazon for English, Shopee for Vietnamese). Empty locales fall back to English, then a contact dialog.
   */
  affiliateUrl?: string | null;
  /**
   * Optional CTA label (defaults to “Shop” / “Mua”).
   */
  linkLabel?: string | null;
  featured?: boolean | null;
  /**
   * Set automatically on first publish. Managers may override.
   */
  publishedAt?: string | null;
  /**
   * Internal ownership for Creator access control. Hidden from public APIs via select.
   */
  owner?: (number | null) | User;
  /**
   * Editorial signal only.
   */
  translationReady?: {
    vi?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Social video links. Cards show R2 thumbnails only — YouTube can auto-import a thumb on save; other platforms need a manual upload.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  title: string;
  provider: 'youtube' | 'tiktok' | 'instagram' | 'other';
  /**
   * Canonical social post URL. YouTube plays inline on click; others open externally.
   */
  sourceUrl: string;
  /**
   * Required for non-YouTube. YouTube auto-imports once on save when empty; you can still upload a custom thumb.
   */
  thumbnail?: (number | null) | Media;
  featured?: boolean | null;
  /**
   * Set automatically on first publish. Managers may override.
   */
  publishedAt?: string | null;
  /**
   * Internal ownership for Creator access control. Hidden from public APIs via select.
   */
  owner?: (number | null) | User;
  /**
   * Editorial signal only.
   */
  translationReady?: {
    vi?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feed-decorations".
 */
export interface FeedDecoration {
  id: number;
  /**
   * Optional label for admin (defaults from filename).
   */
  alt?: string | null;
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * Themed SVG ornament sets for the feed and footer. Activate one from Site settings → Appearance.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "decoration-packs".
 */
export interface DecorationPack {
  id: number;
  /**
   * Admin label (e.g. Plant, New Year).
   */
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Ornaments in this pack. Upload WebP images; they are stored as Feed decorations.
   */
  items?:
    | {
        /**
         * Admin label only (e.g. Monstera leaf).
         */
        title: string;
        /**
         * SVG file stored in R2. Loaded on demand on the public site.
         */
        file: number | FeedDecoration;
        /**
         * Higher weight = more likely to be picked.
         */
        weight?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Which ornament from Items appears in the bottom right corner of the footer while this pack is active.
   */
  footerItem?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Visitor contact form submissions. Email notification is a later enhancement.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  subject?: string | null;
  category?: ('general' | 'project' | 'speaking' | 'other') | null;
  message: string;
  locale: 'en' | 'vi';
  status: 'new' | 'in-progress' | 'resolved' | 'spam' | 'archived';
  assignee?: (number | null) | User;
  /**
   * Staff-only notes. Never exposed publicly.
   */
  internalNotes?: string | null;
  /**
   * Page URL where the form was submitted.
   */
  sourcePage?: string | null;
  consent: boolean;
  /**
   * Non-public abuse metadata. Raw IPs are not stored.
   */
  abuse?: {
    ipHash?: string | null;
    userAgentHash?: string | null;
    honeypotTriggered?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'short-stories';
        value: number | ShortStory;
      } | null)
    | ({
        relationTo: 'feed-decorations';
        value: number | FeedDecoration;
      } | null)
    | ({
        relationTo: 'decoration-packs';
        value: number | DecorationPack;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'things';
        value: number | Thing;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'links';
        value: number | Link;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  active?: T;
  avatar?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  kind?: T;
  sourceUrl?: T;
  dominantColor?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  displayName?: T;
  jobTitle?: T;
  bio?: T;
  avatar?: T;
  website?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  user?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  color?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  relatedPosts?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterCard?: T;
        noIndex?: T;
        noFollow?: T;
        structuredData?:
          | T
          | {
              headline?: T;
              description?: T;
              jsonLdOverride?: T;
            };
      };
  author?: T;
  categories?: T;
  tags?: T;
  featured?: T;
  readingTime?: T;
  publishedAt?: T;
  originalPublishedAt?: T;
  owner?: T;
  translationReady?:
    | T
    | {
        vi?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "short-stories_select".
 */
export interface ShortStoriesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  variant?: T;
  image?: T;
  link?:
    | T
    | {
        enabled?: T;
        label?: T;
        linkType?: T;
        page?: T;
        url?: T;
        newTab?: T;
      };
  publishedAt?: T;
  owner?: T;
  translationReady?:
    | T
    | {
        vi?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feed-decorations_select".
 */
export interface FeedDecorationsSelect<T extends boolean = true> {
  alt?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "decoration-packs_select".
 */
export interface DecorationPacksSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  items?:
    | T
    | {
        title?: T;
        file?: T;
        weight?: T;
        id?: T;
      };
  footerItem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  summary?: T;
  content?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  relatedProjects?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterCard?: T;
        noIndex?: T;
        noFollow?: T;
      };
  author?: T;
  categories?: T;
  tags?: T;
  featured?: T;
  publishedAt?: T;
  owner?: T;
  translationReady?:
    | T
    | {
        vi?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "things_select".
 */
export interface ThingsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  primaryImage?: T;
  detailImage?: T;
  affiliateUrl?: T;
  linkLabel?: T;
  featured?: T;
  publishedAt?: T;
  owner?: T;
  translationReady?:
    | T
    | {
        vi?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  provider?: T;
  sourceUrl?: T;
  thumbnail?: T;
  featured?: T;
  publishedAt?: T;
  owner?: T;
  translationReady?:
    | T
    | {
        vi?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  summary?: T;
  pageImage?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              label?: T;
              title?: T;
              tagline?: T;
              bio?: T;
              heroImage?: T;
              links?: T;
              cursorPopup?: T;
              id?: T;
              blockName?: T;
            };
        feedSection?:
          | T
          | {
              heading?: T;
              description?: T;
              feedType?: T;
              source?: T;
              pagination?: T;
              limit?: T;
              showViewAll?: T;
              viewAllLabel?: T;
              viewAllPage?: T;
              postItems?: T;
              projectItems?: T;
              thingItems?: T;
              videoItems?: T;
              cursorPopup?: T;
              cursorPopupEmpty?: T;
              cursorPopupItem?: T;
              cursorPopupViewAll?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        media?:
          | T
          | {
              media?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              heading?: T;
              body?: T;
              links?: T;
              id?: T;
              blockName?: T;
            };
        projectsGrid?:
          | T
          | {
              heading?: T;
              items?: T;
              featuredOnly?: T;
              id?: T;
              blockName?: T;
            };
        typewriter?:
          | T
          | {
              stories?: T;
              id?: T;
              blockName?: T;
            };
        'scramble-hover'?:
          | T
          | {
              stories?: T;
              id?: T;
              blockName?: T;
            };
        blankSpace?:
          | T
          | {
              height?: T;
              id?: T;
              blockName?: T;
            };
        footer?:
          | T
          | {
              footerText?: T;
              legalLinks?: T;
              copyright?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterCard?: T;
        noIndex?: T;
        noFollow?: T;
      };
  template?: T;
  publishedAt?: T;
  translationReady?:
    | T
    | {
        vi?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links_select".
 */
export interface LinksSelect<T extends boolean = true> {
  label?: T;
  category?: T;
  linkType?: T;
  page?: T;
  url?: T;
  newTab?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  category?: T;
  message?: T;
  locale?: T;
  status?: T;
  assignee?: T;
  internalNotes?: T;
  sourcePage?: T;
  consent?: T;
  abuse?:
    | T
    | {
        ipHash?: T;
        userAgentHash?: T;
        honeypotTriggered?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide identity, navigation, footer, appearance, analytics, and default SEO.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Short line under the site name.
   */
  tagline?: string | null;
  description?: string | null;
  /**
   * Canonical production site URL (no trailing slash preferred).
   */
  siteUrl: string;
  contactEmail?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  /**
   * Website, social, and other profile links (contact dialogs, etc.).
   */
  profileLinks?: (number | Link)[] | null;
  /**
   * Pick links from the Links collection. Each item may have one nested level of children.
   */
  navigation?:
    | {
        /**
         * Pick a link from the Links collection.
         */
        link: number | Link;
        /**
         * One nested level only.
         */
        children?:
          | {
              link: number | Link;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Which decoration pack fills leftover bento gaps and supplies the footer SVG via its footer item.
   */
  activeDecorationPack: number | DecorationPack;
  analytics?: {
    provider?: ('none' | 'plausible' | 'umami' | 'ga' | 'other') | null;
    /**
     * Placeholder for analytics site/measurement ID.
     */
    siteId?: string | null;
  };
  defaultSocialImage?: (number | null) | Media;
  robots?: {
    indexSite?: boolean | null;
  };
  /**
   * Search and social metadata. Frontend rendering (meta tags, sitemap, hreflang) comes later.
   */
  seo?: {
    /**
     * Recommended 50–60 characters. Falls back to document title.
     */
    metaTitle?: string | null;
    /**
     * Recommended 140–160 characters. Falls back to excerpt/summary.
     */
    metaDescription?: string | null;
    /**
     * Optional absolute canonical URL override.
     */
    canonicalUrl?: string | null;
    /**
     * Open Graph title override. Falls back to meta title / title.
     */
    ogTitle?: string | null;
    /**
     * Open Graph description override.
     */
    ogDescription?: string | null;
    /**
     * Open Graph image. Falls back to the page image.
     */
    ogImage?: (number | null) | Media;
    twitterCard?: ('summary' | 'summary_large_image') | null;
    /**
     * Prevent search engines from indexing this document.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  description?: T;
  siteUrl?: T;
  contactEmail?: T;
  bio?: T;
  coverImage?: T;
  profileLinks?: T;
  navigation?:
    | T
    | {
        link?: T;
        children?:
          | T
          | {
              link?: T;
              id?: T;
            };
        id?: T;
      };
  activeDecorationPack?: T;
  analytics?:
    | T
    | {
        provider?: T;
        siteId?: T;
      };
  defaultSocialImage?: T;
  robots?:
    | T
    | {
        indexSite?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterCard?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'short-stories';
          value: number | ShortStory;
        } | null)
      | ({
          relationTo: 'projects';
          value: number | Project;
        } | null)
      | ({
          relationTo: 'things';
          value: number | Thing;
        } | null)
      | ({
          relationTo: 'videos';
          value: number | Video;
        } | null)
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}