import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-d1-sqlite'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`posts_blocks_layout_hero_locales\` RENAME COLUMN "label" TO "label_title";`)
  await db.run(sql`ALTER TABLE \`_posts_v_blocks_layout_hero_locales\` RENAME COLUMN "label" TO "label_title";`)
  await db.run(sql`ALTER TABLE \`projects_blocks_layout_hero_locales\` RENAME COLUMN "label" TO "label_title";`)
  await db.run(sql`ALTER TABLE \`_projects_v_blocks_layout_hero_locales\` RENAME COLUMN "label" TO "label_title";`)
  await db.run(sql`ALTER TABLE \`pages_blocks_layout_hero_locales\` RENAME COLUMN "label" TO "label_title";`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_layout_hero_locales\` RENAME COLUMN "label" TO "label_title";`)
  await db.run(sql`ALTER TABLE \`posts_blocks_layout_hero_locales\` ADD \`label_tagline\` text;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_layout_hero_locales\` ADD \`label_bio\` text;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_layout_hero_locales\` ADD \`label_social_links\` text;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_layout_hero_locales\` ADD \`label_other_links\` text;`)
  await db.run(sql`ALTER TABLE \`_posts_v_blocks_layout_hero_locales\` ADD \`label_tagline\` text;`)
  await db.run(sql`ALTER TABLE \`_posts_v_blocks_layout_hero_locales\` ADD \`label_bio\` text;`)
  await db.run(sql`ALTER TABLE \`_posts_v_blocks_layout_hero_locales\` ADD \`label_social_links\` text;`)
  await db.run(sql`ALTER TABLE \`_posts_v_blocks_layout_hero_locales\` ADD \`label_other_links\` text;`)
  await db.run(sql`ALTER TABLE \`projects_blocks_layout_hero_locales\` ADD \`label_tagline\` text;`)
  await db.run(sql`ALTER TABLE \`projects_blocks_layout_hero_locales\` ADD \`label_bio\` text;`)
  await db.run(sql`ALTER TABLE \`projects_blocks_layout_hero_locales\` ADD \`label_social_links\` text;`)
  await db.run(sql`ALTER TABLE \`projects_blocks_layout_hero_locales\` ADD \`label_other_links\` text;`)
  await db.run(sql`ALTER TABLE \`_projects_v_blocks_layout_hero_locales\` ADD \`label_tagline\` text;`)
  await db.run(sql`ALTER TABLE \`_projects_v_blocks_layout_hero_locales\` ADD \`label_bio\` text;`)
  await db.run(sql`ALTER TABLE \`_projects_v_blocks_layout_hero_locales\` ADD \`label_social_links\` text;`)
  await db.run(sql`ALTER TABLE \`_projects_v_blocks_layout_hero_locales\` ADD \`label_other_links\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_layout_hero_locales\` ADD \`label_tagline\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_layout_hero_locales\` ADD \`label_bio\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_layout_hero_locales\` ADD \`label_social_links\` text;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_layout_hero_locales\` ADD \`label_other_links\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_layout_hero_locales\` ADD \`label_tagline\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_layout_hero_locales\` ADD \`label_bio\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_layout_hero_locales\` ADD \`label_social_links\` text;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_layout_hero_locales\` ADD \`label_other_links\` text;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`ALTER TABLE \`posts_blocks_layout_hero_locales\` RENAME COLUMN "label_title" TO "label";`)
  await db.run(sql`ALTER TABLE \`_posts_v_blocks_layout_hero_locales\` RENAME COLUMN "label_title" TO "label";`)
  await db.run(sql`ALTER TABLE \`projects_blocks_layout_hero_locales\` RENAME COLUMN "label_title" TO "label";`)
  await db.run(sql`ALTER TABLE \`_projects_v_blocks_layout_hero_locales\` RENAME COLUMN "label_title" TO "label";`)
  await db.run(sql`ALTER TABLE \`pages_blocks_layout_hero_locales\` RENAME COLUMN "label_title" TO "label";`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_layout_hero_locales\` RENAME COLUMN "label_title" TO "label";`)
  await db.run(sql`ALTER TABLE \`posts_blocks_layout_hero_locales\` DROP COLUMN \`label_tagline\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_layout_hero_locales\` DROP COLUMN \`label_bio\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_layout_hero_locales\` DROP COLUMN \`label_social_links\`;`)
  await db.run(sql`ALTER TABLE \`posts_blocks_layout_hero_locales\` DROP COLUMN \`label_other_links\`;`)
  await db.run(sql`ALTER TABLE \`_posts_v_blocks_layout_hero_locales\` DROP COLUMN \`label_tagline\`;`)
  await db.run(sql`ALTER TABLE \`_posts_v_blocks_layout_hero_locales\` DROP COLUMN \`label_bio\`;`)
  await db.run(sql`ALTER TABLE \`_posts_v_blocks_layout_hero_locales\` DROP COLUMN \`label_social_links\`;`)
  await db.run(sql`ALTER TABLE \`_posts_v_blocks_layout_hero_locales\` DROP COLUMN \`label_other_links\`;`)
  await db.run(sql`ALTER TABLE \`projects_blocks_layout_hero_locales\` DROP COLUMN \`label_tagline\`;`)
  await db.run(sql`ALTER TABLE \`projects_blocks_layout_hero_locales\` DROP COLUMN \`label_bio\`;`)
  await db.run(sql`ALTER TABLE \`projects_blocks_layout_hero_locales\` DROP COLUMN \`label_social_links\`;`)
  await db.run(sql`ALTER TABLE \`projects_blocks_layout_hero_locales\` DROP COLUMN \`label_other_links\`;`)
  await db.run(sql`ALTER TABLE \`_projects_v_blocks_layout_hero_locales\` DROP COLUMN \`label_tagline\`;`)
  await db.run(sql`ALTER TABLE \`_projects_v_blocks_layout_hero_locales\` DROP COLUMN \`label_bio\`;`)
  await db.run(sql`ALTER TABLE \`_projects_v_blocks_layout_hero_locales\` DROP COLUMN \`label_social_links\`;`)
  await db.run(sql`ALTER TABLE \`_projects_v_blocks_layout_hero_locales\` DROP COLUMN \`label_other_links\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_layout_hero_locales\` DROP COLUMN \`label_tagline\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_layout_hero_locales\` DROP COLUMN \`label_bio\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_layout_hero_locales\` DROP COLUMN \`label_social_links\`;`)
  await db.run(sql`ALTER TABLE \`pages_blocks_layout_hero_locales\` DROP COLUMN \`label_other_links\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_layout_hero_locales\` DROP COLUMN \`label_tagline\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_layout_hero_locales\` DROP COLUMN \`label_bio\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_layout_hero_locales\` DROP COLUMN \`label_social_links\`;`)
  await db.run(sql`ALTER TABLE \`_pages_v_blocks_layout_hero_locales\` DROP COLUMN \`label_other_links\`;`)
}
