import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-d1-sqlite'

// External table that mirrors Payload slugs across locales so slug conflicts are
// caught in a unique index instead of leaking through Payload's localized slug
// fields (which only enforce uniqueness per locale + per parent row, not across
// siblings of the same collection).
//
// Kept in its own migration because it is not generated by Payload's schema
// introspection. See src/hooks/slugReservations.ts (writer) and
// src/app/(frontend)/_lib/page-data.ts (reader).
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.run(sql`CREATE TABLE \`slug_reservations\` (
  	\`id\` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  	\`locale\` text NOT NULL,
  	\`slug\` text NOT NULL,
  	\`collection\` text NOT NULL,
  	\`content_id\` integer NOT NULL
  );
  `)
  await db.run(sql`CREATE UNIQUE INDEX \`slug_reservations_unique\` ON \`slug_reservations\` (\`collection\`,\`locale\`,\`slug\`);`)
  await db.run(sql`CREATE INDEX \`slug_reservations_slug_locale_idx\` ON \`slug_reservations\` (\`slug\`,\`locale\`);`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.run(sql`DROP INDEX IF EXISTS \`slug_reservations_slug_locale_idx\`;`)
  await db.run(sql`DROP INDEX IF EXISTS \`slug_reservations_unique\`;`)
  await db.run(sql`DROP TABLE \`slug_reservations\`;`)
}
