/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    authors: Author;
    categories: Category;
    tags: Tag;
    posts: Post;
    projects: Project;
    pages: Page;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'vi') | ('en' | 'vi')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
    footer: Footer;
    homepage: Homepage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
  };
  locale: 'en' | 'vi';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Authentication accounts. Only Admins can manage users and roles.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * admin: full access · manager: editorial · creator: own drafts only
   */
  role: 'admin' | 'manager' | 'creator';
  /**
   * Inactive users cannot log in or access the Admin panel.
   */
  active?: boolean | null;
  avatar?: (number | null) | Media;
  /**
   * Private notes visible to Admins only.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Files stored in Cloudflare R2. SVG uploads are disallowed. Crop/focal-point transforms are disabled (no sharp on Workers).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Required accessibility text for images.
   */
  alt: string;
  caption?: string | null;
  credit?: string | null;
  kind?: ('image' | 'document' | 'video' | 'other') | null;
  /**
   * Optional original source URL for attribution.
   */
  sourceUrl?: string | null;
  /**
   * Optional #RRGGBB placeholder color for progressive loading.
   */
  dominantColor?: string | null;
  uploadedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * Public-safe author profiles. Never expose auth emails or roles here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  displayName: string;
  jobTitle?: string | null;
  bio?: string | null;
  avatar?: (number | null) | Media;
  website?: string | null;
  socialLinks?:
    | {
        platform: 'github' | 'linkedin' | 'x' | 'youtube' | 'facebook' | 'instagram' | 'website' | 'other';
        url: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Linked auth user (Admin only).
   */
  user?: (number | null) | User;
  /**
   * Only approved profiles are publicly readable.
   */
  approved?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  /**
   * Optional hex color, e.g. #3366FF
   */
  color?: string | null;
  icon?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  /**
   * Short summary used in listings and SEO fallbacks.
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  author?: (number | null) | Author;
  categories?: (number | Category)[] | null;
  tags?: (number | Tag)[] | null;
  relatedPosts?: (number | Post)[] | null;
  featured?: boolean | null;
  /**
   * Estimated minutes; calculated from content.
   */
  readingTime?: number | null;
  /**
   * Set automatically on first publish. Managers may override.
   */
  publishedAt?: string | null;
  /**
   * Optional original publication date if republishing older content.
   */
  originalPublishedAt?: string | null;
  /**
   * Internal ownership for Creator access control. Hidden from public APIs via select.
   */
  owner?: (number | null) | User;
  /**
   * Editorial signal only. Payload `_status` is document-level; locales are field-level.
   */
  translationReady?: {
    vi?: boolean | null;
  };
  /**
   * Search and social metadata. Frontend rendering (meta tags, sitemap, hreflang) comes later.
   */
  seo?: {
    /**
     * Recommended 50–60 characters. Falls back to document title.
     */
    metaTitle?: string | null;
    /**
     * Recommended 140–160 characters. Falls back to excerpt/summary.
     */
    metaDescription?: string | null;
    /**
     * Optional absolute canonical URL override.
     */
    canonicalUrl?: string | null;
    /**
     * Open Graph title override. Falls back to meta title / title.
     */
    ogTitle?: string | null;
    /**
     * Open Graph description override.
     */
    ogDescription?: string | null;
    /**
     * Open Graph image override. Falls back to featured/cover image.
     */
    ogImage?: (number | null) | Media;
    twitterCard?: ('summary' | 'summary_large_image') | null;
    /**
     * Prevent search engines from indexing this document.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
    structuredData?: {
      /**
       * JSON-LD headline override.
       */
      headline?: string | null;
      description?: string | null;
      /**
       * Optional raw JSON-LD object (Admin/Manager only). Must be valid JSON.
       */
      jsonLdOverride?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  summary: string;
  challenge?: string | null;
  solution?: string | null;
  outcome?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  demoUrl?: string | null;
  /**
   * Hide or omit if the repository is private/confidential.
   */
  repositoryUrl?: string | null;
  documentationUrl?: string | null;
  repositoryPrivate?: boolean | null;
  client?: string | null;
  clientConfidential?: boolean | null;
  projectType?: ('web' | 'mobile' | 'library' | 'infra' | 'design' | 'other') | null;
  projectStatus?: ('in-progress' | 'completed' | 'archived' | 'concept') | null;
  startDate?: string | null;
  endDate?: string | null;
  relatedProjects?: (number | Project)[] | null;
  results?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  author?: (number | null) | Author;
  contributors?: (number | Author)[] | null;
  featured?: boolean | null;
  order?: number | null;
  /**
   * Set automatically on first publish. Managers may override.
   */
  publishedAt?: string | null;
  /**
   * Internal ownership for Creator access control. Hidden from public APIs via select.
   */
  owner?: (number | null) | User;
  /**
   * Editorial signal only. Payload `_status` is document-level; locales are field-level.
   */
  translationReady?: {
    vi?: boolean | null;
  };
  /**
   * Search and social metadata. Frontend rendering (meta tags, sitemap, hreflang) comes later.
   */
  seo?: {
    /**
     * Recommended 50–60 characters. Falls back to document title.
     */
    metaTitle?: string | null;
    /**
     * Recommended 140–160 characters. Falls back to excerpt/summary.
     */
    metaDescription?: string | null;
    /**
     * Optional absolute canonical URL override.
     */
    canonicalUrl?: string | null;
    /**
     * Open Graph title override. Falls back to meta title / title.
     */
    ogTitle?: string | null;
    /**
     * Open Graph description override.
     */
    ogDescription?: string | null;
    /**
     * Open Graph image override. Falls back to featured/cover image.
     */
    ogImage?: (number | null) | Media;
    twitterCard?: ('summary' | 'summary_large_image') | null;
    /**
     * Prevent search engines from indexing this document.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  summary?: string | null;
  /**
   * Stable template key for the future frontend. No styling encoded here.
   */
  template: 'home' | 'about' | 'contact' | 'generic';
  heroMedia?: (number | null) | Media;
  layout?:
    | (
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            media: number | Media;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'media';
          }
        | {
            heading: string;
            body?: string | null;
            links?:
              | {
                  label: string;
                  linkType: 'internal' | 'external';
                  page?: (number | null) | Page;
                  url?: string | null;
                  newTab?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
        | {
            heading?: string | null;
            items?: (number | Project)[] | null;
            featuredOnly?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'projectsGrid';
          }
      )[]
    | null;
  /**
   * Set automatically on first publish. Managers may override.
   */
  publishedAt?: string | null;
  /**
   * Editorial signal only. Payload `_status` is document-level; locales are field-level.
   */
  translationReady?: {
    vi?: boolean | null;
  };
  /**
   * Search and social metadata. Frontend rendering (meta tags, sitemap, hreflang) comes later.
   */
  seo?: {
    /**
     * Recommended 50–60 characters. Falls back to document title.
     */
    metaTitle?: string | null;
    /**
     * Recommended 140–160 characters. Falls back to excerpt/summary.
     */
    metaDescription?: string | null;
    /**
     * Optional absolute canonical URL override.
     */
    canonicalUrl?: string | null;
    /**
     * Open Graph title override. Falls back to meta title / title.
     */
    ogTitle?: string | null;
    /**
     * Open Graph description override.
     */
    ogDescription?: string | null;
    /**
     * Open Graph image override. Falls back to featured/cover image.
     */
    ogImage?: (number | null) | Media;
    twitterCard?: ('summary' | 'summary_large_image') | null;
    /**
     * Prevent search engines from indexing this document.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Visitor contact form submissions. Email notification is a later enhancement.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  subject?: string | null;
  category?: ('general' | 'project' | 'speaking' | 'other') | null;
  message: string;
  locale: 'en' | 'vi';
  status: 'new' | 'in-progress' | 'resolved' | 'spam' | 'archived';
  assignee?: (number | null) | User;
  /**
   * Staff-only notes. Never exposed publicly.
   */
  internalNotes?: string | null;
  /**
   * Page URL where the form was submitted.
   */
  sourcePage?: string | null;
  consent: boolean;
  /**
   * Non-public abuse metadata. Raw IPs are not stored.
   */
  abuse?: {
    ipHash?: string | null;
    userAgentHash?: string | null;
    honeypotTriggered?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  active?: T;
  avatar?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  kind?: T;
  sourceUrl?: T;
  dominantColor?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  displayName?: T;
  jobTitle?: T;
  bio?: T;
  avatar?: T;
  website?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  user?: T;
  approved?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  color?: T;
  icon?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  author?: T;
  categories?: T;
  tags?: T;
  relatedPosts?: T;
  featured?: T;
  readingTime?: T;
  publishedAt?: T;
  originalPublishedAt?: T;
  owner?: T;
  translationReady?:
    | T
    | {
        vi?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterCard?: T;
        noIndex?: T;
        noFollow?: T;
        structuredData?:
          | T
          | {
              headline?: T;
              description?: T;
              jsonLdOverride?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  summary?: T;
  challenge?: T;
  solution?: T;
  outcome?: T;
  content?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  demoUrl?: T;
  repositoryUrl?: T;
  documentationUrl?: T;
  repositoryPrivate?: T;
  client?: T;
  clientConfidential?: T;
  projectType?: T;
  projectStatus?: T;
  startDate?: T;
  endDate?: T;
  relatedProjects?: T;
  results?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  author?: T;
  contributors?: T;
  featured?: T;
  order?: T;
  publishedAt?: T;
  owner?: T;
  translationReady?:
    | T
    | {
        vi?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterCard?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  summary?: T;
  template?: T;
  heroMedia?: T;
  layout?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        media?:
          | T
          | {
              media?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              heading?: T;
              body?: T;
              links?:
                | T
                | {
                    label?: T;
                    linkType?: T;
                    page?: T;
                    url?: T;
                    newTab?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        projectsGrid?:
          | T
          | {
              heading?: T;
              items?: T;
              featuredOnly?: T;
              id?: T;
              blockName?: T;
            };
      };
  publishedAt?: T;
  translationReady?:
    | T
    | {
        vi?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterCard?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  category?: T;
  message?: T;
  locale?: T;
  status?: T;
  assignee?: T;
  internalNotes?: T;
  sourcePage?: T;
  consent?: T;
  abuse?:
    | T
    | {
        ipHash?: T;
        userAgentHash?: T;
        honeypotTriggered?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide identity, contact display, and default SEO.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  description?: string | null;
  ownerSummary?: string | null;
  /**
   * Canonical production site URL (no trailing slash preferred).
   */
  siteUrl: string;
  contactEmail?: string | null;
  contactPhone?: string | null;
  location?: string | null;
  defaultSocialImage?: (number | null) | Media;
  socialLinks?:
    | {
        platform: 'github' | 'linkedin' | 'x' | 'youtube' | 'facebook' | 'instagram' | 'website' | 'other';
        url: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  analytics?: {
    provider?: ('none' | 'plausible' | 'umami' | 'ga' | 'other') | null;
    /**
     * Placeholder for analytics site/measurement ID.
     */
    siteId?: string | null;
  };
  robots?: {
    indexSite?: boolean | null;
  };
  /**
   * Search and social metadata. Frontend rendering (meta tags, sitemap, hreflang) comes later.
   */
  seo?: {
    /**
     * Recommended 50–60 characters. Falls back to document title.
     */
    metaTitle?: string | null;
    /**
     * Recommended 140–160 characters. Falls back to excerpt/summary.
     */
    metaDescription?: string | null;
    /**
     * Optional absolute canonical URL override.
     */
    canonicalUrl?: string | null;
    /**
     * Open Graph title override. Falls back to meta title / title.
     */
    ogTitle?: string | null;
    /**
     * Open Graph description override.
     */
    ogDescription?: string | null;
    /**
     * Open Graph image override. Falls back to featured/cover image.
     */
    ogImage?: (number | null) | Media;
    twitterCard?: ('summary' | 'summary_large_image') | null;
    /**
     * Prevent search engines from indexing this document.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items?:
    | {
        label: string;
        linkType: 'internal' | 'external';
        page?: (number | null) | Page;
        url?: string | null;
        newTab?: boolean | null;
        /**
         * One nested level only.
         */
        children?:
          | {
              label: string;
              linkType: 'internal' | 'external';
              page?: (number | null) | Page;
              url?: string | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  text?: string | null;
  groups?:
    | {
        title: string;
        links?:
          | {
              label: string;
              linkType: 'internal' | 'external';
              page?: (number | null) | Page;
              url?: string | null;
              newTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform: 'github' | 'linkedin' | 'x' | 'youtube' | 'facebook' | 'instagram' | 'website' | 'other';
        url: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  legalLinks?:
    | {
        label: string;
        linkType: 'internal' | 'external';
        page?: (number | null) | Page;
        url?: string | null;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Use {{year}} as a placeholder for the current year in the frontend.
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Curated homepage content. No frontend styling controls.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  heroHeading: string;
  heroSubheading?: string | null;
  profileSummary?: string | null;
  heroImage?: (number | null) | Media;
  featuredPosts?: (number | Post)[] | null;
  featuredProjects?: (number | Project)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  description?: T;
  ownerSummary?: T;
  siteUrl?: T;
  contactEmail?: T;
  contactPhone?: T;
  location?: T;
  defaultSocialImage?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  analytics?:
    | T
    | {
        provider?: T;
        siteId?: T;
      };
  robots?:
    | T
    | {
        indexSite?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        twitterCard?: T;
        noIndex?: T;
        noFollow?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        linkType?: T;
        page?: T;
        url?: T;
        newTab?: T;
        children?:
          | T
          | {
              label?: T;
              linkType?: T;
              page?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  text?: T;
  groups?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              linkType?: T;
              page?: T;
              url?: T;
              newTab?: T;
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        linkType?: T;
        page?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  heroHeading?: T;
  heroSubheading?: T;
  profileSummary?: T;
  heroImage?: T;
  featuredPosts?: T;
  featuredProjects?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null)
      | ({
          relationTo: 'projects';
          value: number | Project;
        } | null)
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}